version: "3.5"

services:
  user-service:
    container_name: user-service
    image: user-service
    # environment:
    #   db_host: postgres
    ports:
      - "8080:8080"
    networks:
      - network1

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - network1
    restart: unless-stopped

networks:
  network1:
    driver: bridge

volumes:
  postgres:
