version: "3.5"

services:
  user-service:
    container_name: user-service
    image: user-service
    environment:
      DB_HOST: postgres
    ports:
      - "8080:8080"
    networks:
      - network1
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - postgres:/data/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    networks:
      - network1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  network1:
    driver: bridge

volumes:
  postgres:
