FROM golang:1.25-bookworm AS base
WORKDIR /app
COPY go.* .
RUN go mod download
COPY . .

FROM base AS test
RUN go test ./...

FROM base AS build
ENV CGO_ENABLED=0
RUN go build -v -o server

FROM alpine:3.23
# ENV GIN_MODE=release
RUN apk add --no-cache curl

HEALTHCHECK --start-period=10s --interval=30s --timeout=5s \
    CMD curl -f http://localhost:8040/health || exit 1

WORKDIR /app
COPY --from=build /app/server .
COPY --from=build /app/config.json .

EXPOSE 8040
CMD ["/app/server"]
