FROM golang:1.22-bookworm AS builder
WORKDIR /app
COPY go.* .
RUN go mod download

COPY . .

RUN go build -v -o server

FROM debian:bookworm-slim
RUN set -x && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    ca-certificates && \
    rm -rf /var/lib/apt/lists/*

ENV CGO_ENABLED=0

EXPOSE 8080

WORKDIR /app
COPY --from=builder /app/server .
COPY --from=builder /app/config.json .
CMD ["/app/server"]